- include: ../../common/tasks/setfacts.yml
  tags:
    - namedata
    - deploy
    - config

- name: Unstall unzip (Debian only)
  apt: pkg=unzip state=present
  when: ansible_os_family == "Debian"

- name: ensure target directories exist [data subdirectories etc.]
  when: nameindex_variant == "ala"
  file: path={{ data_dir }}/bie/import/{{item}} state=directory owner={{tomcat_user}} group={{tomcat_user}}
  with_items: "{{ala_name_sources}}"
  tags:
    - config
    - namedata

- name: get source name data from ALA
  when: nameindex_variant == "ala"
  get_url: url={{ala_name_indexes_repo}}/{{item}}-{{name_index_date}}.zip dest={{data_dir}}/bie/import force={{ force_nameindex_download | default(false) }}
  with_items: "{{ala_name_sources}}"
  tags:
    - config
    - namedata

- name: unpackage source name data
  when: nameindex_variant == "ala"
  unarchive: src={{data_dir}}/bie/import/{{item}}-{{name_index_date}}.zip dest={{data_dir}}/bie/import/{{item}} owner={{tomcat_user}} group={{tomcat_user}} copy=no
  with_items: "{{ala_name_sources}}"
  tags:
    - config
    - namedata
